### ISSUE TITLE
Remove MessageSend

### ISSUE THREAD

**Issue by flbulgarelli** [uqbar-project/arena#13]
Now we are using arena only from languages that have static typing and lambdas/blocks, but MessageSend is largerly a patch for the lack of lambdas, in a dynamic typed way. 

Perhaps it is time to remove that class, since it only adds confussion to framework users.

**Comment by fdodino** [comment]
¿Qué onda con ésto? Lo sigo viendo en el pull que hice hoy. Está en un branch? @flbulgarelli  @faloi @javierfernandes @npasserini

**Comment by npasserini** [comment]
Ni idea, hace bocha no toco Arena.

**Comment by npasserini** [comment]
¿Y? ¿Lo borraron?

**Comment by fdodino** [comment]
¡Así es! Por eso ahora Arena requiere Java 1.8

**Comment by javierfernandes** [comment]
Esto es un poco polémico para mí.

Me parece muy simpático como maneja esto xtend, que si un método recibe una
interface que tiene un sólo método, entonces convierte automática (y
estáticamente) un bloque a esa interface y viceversa.

A mí me gusta porque.. al momento de usarlo, muchas veces es obvio que es
más cómodo usar un bloque que una inner o una clase.
Pero, también pasa que si empiezo a diseñar algo más complejo, como tener
ya bloques de cosas a hacer según algún otro criterio (y tal vez modelo eso
como un bloque) entonces mi código empieza a ser ilegible, a lo
predicador-funcional.

Map<(Object)=>Boolean, List<(Object)=>void)>

O sea.. ya no tengo que empezar a poner javadocs por todos lados porque no
se entiende la función o la intención.
Es como modelar todo con colecciones.

A nivel de definir una interfaz me resulta más claro tener interfaces con
nombres y javadocs.

En fin.

**Comment by npasserini** [comment]
Pero creo que no es tan así, Javi. MessageSend era una implementación
específica de una interfaz (Action). Hasta donde yo entiendo Action sigue
existiendo, ¿no es así?

2016-08-11 14:19 GMT+02:00 javierfernandes <notifications@github.com>:

**Comment by javierfernandes** [comment]
Ah.. bien entonces.. Mala mía

2016-08-11 10:39 GMT-03:00 Nico Passerini <notifications@github.com>:

**Comment by fdodino** [comment]
Sí, la interfaz IAction o Action (no recuerdo ahora) sigue existiendo y es la que hace que uno pueda usar el chiche de definir un bloque y xtend haga su gracia de castearlo a Action.

La motivación para sacar el MessageSend fue para forzar este año a los alumnos de Diseño a usar Java 1.8
En PAIU no tiene tanto sentido porque usamos Xtend tanto en UNSAM como en UNQ.
