### ISSUE TITLE
Add code coverage to travis with coveralls

### ISSUE THREAD

**Issue by javierfernandes** [uqbar-project/arena#17]
See wollok project that already has this implemented

**Comment by fdodino** [comment]
Copiar de:
https://github.com/uqbar-project/wollok/blob/master/.travis.yml

**Comment by fdodino** [comment]
Cosas para hacer
1) Importar en el pom de arena jacoco y coveralls
			
			<plugin>
				<groupId>org.jacoco</groupId>
				<artifactId>jacoco-maven-plugin</artifactId>
				<version>0.7.5.201505241946</version>
				<executions>
					<execution>
						<id>prepare-agent</id>
						<goals>
							<goal>prepare-agent</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.eluder.coveralls</groupId>
				<artifactId>coveralls-maven-plugin</artifactId>
				<version>4.1.0</version>

				<configuration>
					<coberturaReports>
						<coberturaReport>
							${basedir}/target/coverage.xml
						</coberturaReport>
					</coberturaReports>
					<sourceEncoding>UTF-8</sourceEncoding>
					<serviceName>travis-ci</serviceName>
					<serviceJobId>${env.TRAVIS_JOB_ID} </serviceJobId>
				</configuration>
			</plugin>
			

2) Agregar en travis el script (copiar de .travis.yml)
script: 
- mvn -DTRAVIS_JOB_ID=$TRAVIS_JOB_ID clean install jacoco:report coveralls:report


3) Entrar a http://coveralls.io y habilitar el repo

4) Incorporar el badge (entrar nuevamente a http://coveralls.io y navegar hasta el repo para luego seleccionar badge your repo)

**Comment by fdodino** [comment]
Primera parte lista.
Falta linkear con tests de Scala porque hay un test coverage del 0,44% :)

**Comment by fdodino** [comment]
Ok con lo de Scala, de hecho hay dos clases que suben un poco el escaso test coverage que hay...
https://coveralls.io/builds/4609523?all=true
Marco el issue como done, y a futuro hay que tratar de subir el % de  test coverage

**Comment by fdodino** [comment]
Ajá, no está tomando los tests de java, por ejemplo en arena-core, no me tomó los tests que le hice a los bootstraps, habrá que averiguar qué pasa.

**Comment by fdodino** [comment]
Falsa alarma, no había tomado el último commit.
