### ISSUE TITLE
Optimize dependency tree

### ISSUE THREAD

**Issue by flbulgarelli** [uqbar-project/arena#4]
Currently this project depends on the following jar:
- scala-library
- apache collections
- generic version of apache collections

And in addition it will be mostly used in project that:
- target compiled to java 8
- are written in XTend
- or depend on Guava

That means that we have no more than 4 collection frameworks, which makes more complex to determine which to use

**Comment by fdodino** [comment]
What about this @flbulgarelli @faloi ?

**Comment by faloi** [comment]
I can roughly remember what I've done last week... 2 years ago is a lot of time. :stuck_out_tongue:

**Comment by fdodino** [comment]
Maybe this will refresh your memory...

![fosfovita](https://cloud.githubusercontent.com/assets/4549002/17588250/f983b85c-5fa3-11e6-862c-4bab036657f9.jpg)

:smile:
