### ISSUE TITLE
Text/numbers cannot be aligned on Labels, Columns and other components

### ISSUE THREAD

**Issue by eschafir** [uqbar-project/arena#40]
Actually is not possible to align text or numbers on different components such as:

- Column
- Label
- Button

**Comment by fdodino** [comment]
Got it @eschafir !



```java
	    new Column<Persona>(tbl)
	      .setTitle("Edad")
	      .setFixedSize(50)
	      .alignRight()
	      .bindContentsToProperty("edad");
``` 

Also default NumericField behavior is right aligned:

![image](https://user-images.githubusercontent.com/4549002/28135691-818a72c8-671d-11e7-8ab7-c92e4f9fd526.png)

Now you can alignLeft, right or center Button, Column or Labels, 
and align right or left texts.
Coming soon for Arena 3.6.2!
